#!/bin/bash

# Setup script for Samurai Jack project
# Configures git hooks and local environment

echo "🚀 Setting up Samurai Jack development environment..."

# Set up git hooks directory
echo "📝 Configuring git hooks..."
git config core.hooksPath .githooks

# Make pre-commit hook executable
chmod +x .githooks/pre-commit

echo "✅ Git hooks configured"

# Create local.properties if it doesn't exist
if [ ! -f "local.properties" ]; then
    echo "📝 Creating local.properties..."
    {
        echo "# Local properties for Samurai Jack"
        echo "# Generated by setup script"
        echo "sdk.dir=$(android list sdk)"
    } > local.properties
fi

# Install dependencies
echo "📦 Installing Gradle dependencies..."
./gradlew --version

echo ""
echo "✨ Setup complete!"
echo ""
echo "Next steps:"
echo "1. Open the project in Android Studio"
echo "2. Sync Gradle files"
echo "3. Connect an Android device or start an emulator"
echo "4. Run './gradlew installDebug' to build and install"
echo ""
echo "Pre-commit hooks are configured. They will run automatically before each commit."
echo "You can run checks manually:"
echo "  ./gradlew ktlintCheck detekt testDebugUnitTest"
echo ""
